### ISSUE TITLE
extract_parameter_set_dials method

### ISSUE THREAD

**Issue by topepo** [tidymodels/tailor#53]
tune is showing errors of 

> Error in `UseMethod("extract_parameter_set_dials")`: no applicable method for 'extract_parameter_set_dials' applied to an object of class "tailor"

I know it hasn't been implemented yet. I'll add skips in the tests for `tailor >= 0.0.0.9002`. Can you bump the version number once that method is implemented?

**Comment by simonpcouch** [comment]
Ah, looks like I forgot to update that Remotes field in tune.
